# Generated by Django 5.2.3 on 2025-07-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_remove_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='telegram_id',
        ),
    ]
