# Generated by Django 5.2.3 on 2025-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('user_code', models.PositiveIntegerField(unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
