# Generated by Django 5.2.3 on 2025-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
