# Generated by Django 5.2.3 on 2025-07-21 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_telegramuser_balance_configuration_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='receipts/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('edited_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_receipts', to='orders.telegramuser')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to='orders.telegramuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
