# Generated by Django 5.2.3 on 2025-07-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_settlementreceipt_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vless_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('total_bytes', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='orders.telegramuser')),
            ],
        ),
    ]
