# Generated by Django 5.2.3 on 2025-07-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_vlessconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlessconfig',
            name='expires_at',
        ),
    ]
