# Generated by Django 5.2.3 on 2025-07-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_vlessconfig_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
