# Generated by Django 5.2.3 on 2025-07-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_telegramuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlessconfig',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vlessconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vlessconfig',
            name='used_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
