# Generated by Django 5.2.3 on 2025-07-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_vlessconfig_expires_at_vlessconfig_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlessconfig',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
